### ISSUE TITLE
Does not work. Only wrote 1GB of file.

### ISSUE THREAD

**Issue by ragvri** [alexandres/terashuf#1]
I had a 100GB of text file. Needed to shuffle it. It reads the file correctly and even created 23 temp files. This is the final message I received:
```

starting read
lines read: 723456445, gb read: 91
Read 723456445 lines, 98466096665 bytes, have 23 tmp files

starting write to output
lines written: 9126923, gb written: 1
done
```

**Comment by alexandres** [comment]
Hi ragvri,

That's odd. In all my tests it works as expected. Can you comment out line 235 in terashuf.cc 
 - unlink(files[i]->path) - then run

$ make
$ mkdir -p output
$ head -c 1000000000  yourinputfile | TMPDIR=output MEMORY=.1 ./terashuf > yourinputfile.shuffled

Does this work as expected? It should output a 1GB file and leave 10 temp files in the ./output dir.

If this works, run 

$ cat  yourinputfile | TMPDIR=output MEMORY=.1 ./terashuf > yourinputfile.shuffled

It should fail like your example but leave 23 tmp files in ./output. Can you check that each is roughly 100/23 GB in size?

Thanks!

**Comment by alexandres** [comment]
I think what's happening is that you don't have enough disk space for the shuffle. I just added a couple of lines that check if your disk is full and reports the error. Can you download the new version and see if it throws a FATAL ERROR on your 100GB file? Thanks!

**Comment by ragvri** [comment]
I shall let you know. I, however, have managed to shuffle the data using some hints from your README. Divided the file into smaller files. Used `shuf` on that. Merged them using `cat`. Nice work though.

**Comment by alexandres** [comment]
Great, please let me know if it works so I can close this issue. 

You should use a terashuf instead of the method you described. If your original file has smaller files A B C D, and you shuffle them individually to get A' B' C' D', there is no shuffling *between* the files. You could do something marginally better to get (for example) C' A' D' B' by shuffling the *files* themselves before the cat, but this is still far from a real shuffle.  terashuf does the right thing, combining chunks from the shuffled files into new shuffled files before doing the merge.

**Comment by ragvri** [comment]
It worked. Sorry for bothering you.

**Comment by alexandres** [comment]
Great!
